version: '3.9'
services:
    user-service:
      build: ./user-service
      ports:
        - "3000:3000"
      networks:
        - yunus-network
    product-service:
      build: ./product-service
      ports:
        - "3001:3001"
      networks:
        - yunus-network
    order-service:
      build: ./order-service
      ports:
        - "3002:3002"
      networks:
        - yunus-network
    gateway-service:
      build: ./gateway-service
      ports:
        - "3003:3003"
      networks:
        - yunus-network

networks:
  yunus-network:
    driver: bridge